name: Blog CI/CD

# 触发条件：在 push 到 hexo-blog-backup 分支后触发
on:
  push:
    branches: 
      - source

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Setup node
      # 设置 node.js 环境
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache node modules
      # 设置包缓存目录，避免每次下载
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install hexo dependencies
      # 下载 hexo-cli 脚手架及相关安装包
      run: |
        npm install -g hexo-cli
        npm install hexo-deployer-git --save
        npm install

    - name: set git env
      env: 
        # Github 仓库
        GITHUB_REPO: git@github.com:AngusLean/AngusLean.github.io.git
        HEXO_DEPLOY_PRI: ${{secrets.DEPLOY_KEY}}
        # Coding 仓库
        # CODING_REPO: e.coding.net/yifanzheng/blogs.git
        # Gitee 仓库
        # GITEE_REPO: gitee.com/yifanzheng/yifangzheng.gitee.io.git
      # 将编译后的博客文件推送到指定仓库
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name "anguslean"
        git config --global user.email "cupofish@email.com"
        
    - name: Generate files And Deploy
      # 编译 markdown 文件
      run: |
        hexo g -d    